# Generated by Django 5.2.5 on 2025-08-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felhasznalonev', models.CharField(max_length=100, unique=True)),
                ('emailcim', models.EmailField(max_length=254, unique=True)),
                ('jelszo', models.CharField(unique=True)),
                ('keszult', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
