# Generated by Django 5.2.5 on 2025-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felhasznalok',
            name='emailcim',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email cím'),
        ),
        migrations.AlterField(
            model_name='felhasznalok',
            name='felhasznalonev',
            field=models.CharField(max_length=100, unique=True, verbose_name='Felhasználónév'),
        ),
        migrations.AlterField(
            model_name='felhasznalok',
            name='jelszo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Jelszó'),
        ),
        migrations.AlterField(
            model_name='felhasznalok',
            name='keszult',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Készült'),
        ),
    ]
